version: '3'

services:
  # Только основное приложение FlappyCoin
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - ./ssl:/app/ssl:ro  # Монтируем сертификаты напрямую
    ports:
      - "80:80"
      - "443:443"
    networks:
      - flappycoin-network

networks:
  flappycoin-network:
    driver: bridge